In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import nltk
import nltk.corpus
from nltk.tokenize import word_tokenize 
from nltk.tokenize import blankline_tokenize 
#nltk.download('punkt')
#nltk.download()

In [4]:
data = pd.read_csv("Dataset/training.csv")

In [5]:
data1 = pd.read_csv("Dataset/test.csv")

In [6]:
sent = data['text'].tolist() + data1['text'].tolist()

In [7]:
len(sent)

20000

In [8]:
print(sent[18000])

im feeling rather rotten so im not very ambitious right now


In [9]:
mystr = ""
for words in sent:
    mystr += ' ' + words

In [10]:
tokens = word_tokenize(mystr)
len(tokens)

382881

In [11]:
from nltk.probability import FreqDist
fdist = FreqDist()

In [12]:
for word in tokens:
    fdist[word.lower()] += 1

In [13]:
fdist

FreqDist({'i': 32242, 'feel': 13938, 'and': 11996, 'to': 11208, 'the': 10462, 'a': 7748, 'feeling': 6431, 'that': 6314, 'of': 6182, 'my': 5326, ...})

In [14]:
top_fdist = fdist.most_common(1000)
top_fdist

[('i', 32242),
 ('feel', 13938),
 ('and', 11996),
 ('to', 11208),
 ('the', 10462),
 ('a', 7748),
 ('feeling', 6431),
 ('that', 6314),
 ('of', 6182),
 ('my', 5326),
 ('in', 4239),
 ('it', 3922),
 ('like', 3616),
 ('so', 3127),
 ('im', 3055),
 ('for', 3021),
 ('me', 2901),
 ('was', 2828),
 ('have', 2803),
 ('but', 2790),
 ('is', 2718),
 ('this', 2606),
 ('am', 2591),
 ('with', 2530),
 ('not', 2401),
 ('about', 2249),
 ('be', 2193),
 ('as', 1945),
 ('on', 1925),
 ('you', 1878),
 ('just', 1814),
 ('at', 1728),
 ('when', 1689),
 ('or', 1564),
 ('all', 1456),
 ('because', 1433),
 ('more', 1396),
 ('do', 1312),
 ('can', 1298),
 ('really', 1182),
 ('up', 1165),
 ('t', 1156),
 ('by', 1108),
 ('are', 1104),
 ('very', 1086),
 ('know', 1080),
 ('been', 1056),
 ('if', 1046),
 ('out', 1024),
 ('myself', 1004),
 ('time', 993),
 ('what', 984),
 ('how', 957),
 ('little', 932),
 ('get', 926),
 ('had', 898),
 ('will', 887),
 ('now', 878),
 ('from', 876),
 ('they', 855),
 ('being', 849),
 ('people', 839),

In [15]:
from nltk.corpus import stopwords

In [16]:
mystopw = []
templist1 = fdist.most_common(50)
for i in range(50):
    mystopw.append(templist1[i][0])

In [17]:
for w in stopwords.words('english'):
    if w not in mystopw:
        mystopw.append(w)

In [18]:
len(mystopw)

185

In [19]:
n = len(data)
print(n)

18000


In [20]:
n1 = len(data1)

In [21]:
import re
punctuation = re.compile(r'[-.?!,:;()|0-9]')

In [22]:
ppr_data = []
for i in range(n):
    str1 = data['text'][i]
    str2 = word_tokenize(str1)
    str3 = []
    for str2_words in str2:
        str2_lemmatized = nltk.stem.WordNetLemmatizer().lemmatize(str2_words)
        '''word1 = punctuation.sub("", str2_lemmatized)
        if len(word1)>0:
            str3.append(word1)'''
        if str2_lemmatized.lower() not in mystopw:
            str3.append(str2_lemmatized)
    ppr_data.append(str3)

In [23]:
for i in range(n1):
    str11 = data1['text'][i]
    str22 = word_tokenize(str11)
    str33 = []
    for str22_words in str22:
        str22_lemmatized = nltk.stem.WordNetLemmatizer().lemmatize(str22_words)
        '''word11 = punctuation.sub("", str22_lemmatized)
        if len(word11)>0:
            str33.append(word11)'''
        if str22_lemmatized.lower() not in mystopw:
            str33.append(str22_lemmatized)
    ppr_data.append(str33)

In [24]:
len(ppr_data)

20000

In [25]:
ppr_data[18000]

['rather', 'rotten', 'ambitious', 'right']

In [26]:
from nltk.probability import FreqDist
fdist = FreqDist()

In [27]:
from nltk.tokenize.treebank import TreebankWordDetokenizer

In [28]:
ppr_data1 = []
for i in range(len(ppr_data)):
    ppr_data1.append(TreebankWordDetokenizer().detokenize(ppr_data[i]))

In [29]:
ppr_data1[18000]

'rather rotten ambitious right'

In [30]:
ppr_data1[-1]

'weird meet w people text dont talk face face w'

In [31]:
x_train = ppr_data1[:18000]
y_train = data['label']

In [32]:
x_train[-1]

'wannabuy cute make see online even one'

In [33]:
x_test = ppr_data1[18000:]

In [34]:
x_test[-1]

'weird meet w people text dont talk face face w'

In [35]:
len(x_train)

18000

In [36]:
len(y_train)

18000

In [37]:
len(x_test)

2000

In [38]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [39]:
vectorizer = TfidfVectorizer(stop_words='english')
vectorizer.fit(x_train)
vector_train = vectorizer.transform(x_train)
vector_test = vectorizer.transform(x_test)
#x_train1.append(vector)

In [40]:
'''vectorizer = TfidfVectorizer(stop_words='english')
vectorizer.fit(x_test)
vector_test = vectorizer.transform(x_test)
#x_train1.append(vector)'''

"vectorizer = TfidfVectorizer(stop_words='english')\nvectorizer.fit(x_test)\nvector_test = vectorizer.transform(x_test)\n#x_train1.append(vector)"

In [41]:
from sklearn.naive_bayes import MultinomialNB

In [42]:
mnb = MultinomialNB()
mnb.fit(vector_train, y_train)
#mnb.predict(vector1)

MultinomialNB()

In [43]:
y_test = mnb.predict(vector_test)

In [44]:
vector_train.shape

(18000, 14122)

In [45]:
vector_test.shape

(2000, 14122)

In [49]:
from sklearn.naive_bayes import GaussianNB

In [50]:
gnb = GaussianNB()

In [51]:
gnb = GaussianNB()
gnb.fit(vector_train.toarray(), y_train)

GaussianNB()

In [52]:
y_test_gnb = gnb.predict(vector_test.toarray())

In [53]:
print(y_test)

[0 0 0 ... 1 1 1]


In [54]:
print(y_test_gnb)

[1 0 4 ... 4 3 2]


In [55]:
df_test = pd.DataFrame(y_test) 
df_test.to_csv('y_test.csv') 

In [56]:
df_test_gnb = pd.DataFrame(y_test_gnb) 
df_test_gnb.to_csv('GaussianNavieBayes.csv') 

In [57]:
from sklearn.naive_bayes import ComplementNB

In [58]:
cnb = ComplementNB()

In [59]:
cnb.fit(vector_train.toarray(), y_train)

ComplementNB()

In [60]:
y_test_cnb = cnb.predict(vector_test.toarray())

In [61]:
print(y_test)

[0 0 0 ... 1 1 1]


In [62]:
print(y_test_cnb)

[0 0 0 ... 1 1 4]


In [63]:
df_test_cnb = pd.DataFrame(y_test_cnb) 
df_test_cnb.to_csv('ComplementNavieBayesResult.csv')